sudo: false

language: perl

perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

install:
    - cpanm Dist::Zilla
    - cpanm Moose::Autobox
    - cpanm Dist::Zilla::PluginBundle::ROKR || { cat ~/.cpanm/build.log ; false ; }
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
    - dzil test --author --release
